/// Generated by json-dart-serializable plugin.
/// When some incorrect data generated, please fix it.
/// Finally, run flutter build_runner auto generate *.g.dart file.
import 'package:json_annotation/json_annotation.dart';

part 'sign_up_response.g.dart';

/// Generated class description...
@JsonSerializable()
class SignUpResponse {
    /// success
    bool? success;

    /// message
    String? message;

    /// data
    String? data;

    /// token
    String? token;


    /// http_status_code
    @JsonKey(name: 'http_status_code')
    int? httpStatusCode;

    String? error;


    /// Constructor...
    SignUpResponse({required this.success, required this.message, required this.data, required this.token, required this.httpStatusCode });
    SignUpResponse.withError(String err):error = err;
    /// Deserializer...
    factory SignUpResponse.fromJson(Map<String, dynamic> json) => _$SignUpResponseFromJson(json);

    /// Serializer...
    Map<String, dynamic> toJson() => _$SignUpResponseToJson(this);
}