/// Generated by json-dart-serializable plugin.
/// When some incorrect data generated, please fix it.
/// Finally, run flutter build_runner auto generate *.g.dart file.
import 'package:json_annotation/json_annotation.dart';

part 'add_certificate_response.g.dart';

/// Generated class description...
@JsonSerializable()
class AddCertificateResponse {
    /// success
    @JsonKey(defaultValue: false)
    bool? success;

    /// message
    @JsonKey(defaultValue: "")
    String? message;

    /// data
    @JsonKey(defaultValue: null)
    String? data;

    /// token
    @JsonKey(defaultValue: null)
    String? token;

    /// http_status_code
    @JsonKey(name: 'http_status_code')
    int? httpStatusCode;

    String? error;




    /// Constructor...
    AddCertificateResponse( { this.success, this.message, this.data,  this.token,  this.httpStatusCode });
    AddCertificateResponse.withError(String err):error = err;
    /// Deserializer...
    factory AddCertificateResponse.fromJson(Map<String, dynamic> json) => _$AddCertificateResponseFromJson(json);

    /// Serializer...
    Map<String, dynamic> toJson() => _$AddCertificateResponseToJson(this);
}